service: assignment-cognito

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  role: arn:aws:iam::838400343523:role/cognito-lambda
  region: ap-south-1
  


functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
      
